### ISSUE TITLE
SMART is not Defined

### ISSUE THREAD

**Issue by Venkatramanaryams** [smart-on-fhir/growth-chart-app#47] opened 2018-10-04 04:30 UTC
Hello...
I am trying to integrate the Growth chart on Java Based Web application. I am enabled local storage of Firefox 47.0. but SMART is  not connected.
@nschwertner @vlad-ignatov @dpopcmh  can you guys help out from  this issue

**Comment by vlad-ignatov** [comment] 2018-10-04 12:38
This is a duplicate of #46

**Closed by vlad-ignatov** 2018-10-04 12:38 UTC
